### ISSUE TITLE
Upload image error 

### ISSUE THREAD

**Issue by medbz** [Meg4R0M/eCommerce_Symfony_3#1]
Hello I am using your project to create my own website everything run well but when i try to upload an image using admin panel i get this error 
```
Could not determine access type for property "file".
500 Internal Server Error - NoSuchPropertyException
```

Any help please ?

**Comment by psykoterro** [comment]
Hi ! 
you just need to give good right to web/uploads & web/media (chmod 777).

Regards,
Meg4R0M

**Comment by medbz** [comment]
```
-rwxr-xr-x@  1 user  staff    631 Jan  9  2017 app.php
-rwxr-xr-x@  1 user  staff   1178 Jan  9  2017 app_dev.php
-rwxr-xr-x@  1 user  staff  11478 Jan  9  2017 apple-touch-icon.png
-rwxr-xr-x@  1 user  staff  21244 Jan  9  2017 config.php
drwxr-xr-x@ 11 user  staff    374 Jan  9  2017 css
-rwxr-xr-x@  1 user  staff   4158 Jan  9  2017 favicon.ico
drwxr-xr-x@  9 user  staff    306 Jan  9  2017 img
drwxr-xr-x@ 12 user  staff    408 Jan  9  2017 js
drwxrwxrwx@  4 user  staff    136 Mar  1 22:46 media
-rwxr-xr-x@  1 user  staff    116 Jan  9  2017 robots.txt
drwxrwxrwx@ 25 user  staff    850 Mar  1 22:50 uploads
```

**Comment by psykoterro** [comment]
I will investigate about these error and i come back =)

**Comment by medbz** [comment]
Thank you 👍

**Comment by psykoterro** [comment]
Project updated, tested, all work fine. This problem was resolved on Canturla branch's (https://stackoverflow.com/questions/41213014/could-not-determine-access-type-for-property-file) and now i've merged Canturla on master. Please use git pull.

Regards
